### ISSUE TITLE
[1.15.2] Stone Circles potentially causing massive TPS lag followed by Watchdog crash.

### ISSUE THREAD

**Issue by ridjack** [svenhjol/Strange#15]
[crash-2020-04-04_17.26.04-server.txt](https://github.com/svenhjol/Strange/files/4432583/crash-2020-04-04_17.26.04-server.txt)

**Comment by svenhjol** [comment]
what did you do to trigger this?

**Comment by ridjack** [comment]
Nothing specific as far as I can tell; my wife and I moved into an area that had been loaded previously. We've not yet been able to actually make use of any portion of the runestones module, though we have seen quite a few Stone Circles.

**Comment by svenhjol** [comment]
Ok thanks. I'd expect it if you'd used an enderpearl on a runestone and the game was trying to find a structure that wasn't enabled. Same goes for if a map was generated to a distant structure and couldn't find it. Do you have structures disabled? Seems odd that it would occur out of the blue, especially in already-loaded chunks.

**Comment by svenhjol** [comment]
I lurk on Vazkii's discord and also modded minecraft. If you want you can catch me there.

**Comment by dieffenbachj** [comment]
I also have had this problem. The problem went away the moment I disabled Strange.
Each crash log was a simple Watchdog error, and each log had no evidence that it was Strange except for the VERY FIRST one, which spammed this line:

[04Apr2020 15:30:19.055] [Server thread/ERROR] [net.minecraft.world.gen.feature.structure.Structures/]: Unknown structure piece id: minecraft:bigdungeon

Disabling Quark didn't actually solve the problem though, it just made it so that it was crashing without errors.

The TPS starts at 20, and shoots back up if everyone is offline on the server; it's only when people are logged in that it slowly grinds to a halt. 

Disabling Strange fixed it, until we started exploring the world again, when we got a crash related to the game trying to generate a stone circle and that not being a valid structure.

Also note that I've only experienced this in multiplayer; I've done a mountain of exploring and testing of the modpack I'm making in single player, but it was only in multiplayer with a friend that the server started doing this.

**Comment by clootas** [comment]
I have this in singleplayer. Went into a world and just sat there for like 20ish minutes, moved around a bit and I got TPS lag. Only things I had installed were this mod, BoP, and Terraforged. Got rid of strange and it disappeared instantly

**Comment by svenhjol** [comment]
For anyone who is willing to test, please backup your world and run with these files:
* https://github.com/svenhjol/Charm/releases/download/1.15.2-1.5.5/Charm-1.15.2-1.5.5-DEBUG.jar
* https://github.com/svenhjol/Strange/releases/download/1.15.2-1.0.0-beta.2/Strange-1.15.2-1.0.0-beta.2.jar

The above versions should spam debug logs to the main console. If your game crashes, please post the console log here as it will contain more information for me to work with.

@ridjack the linked beta 2 version of Strange has a fix for structures that mean they now obey enable/disable in the config. You might need to enable stone circles again if you're testing.

**Comment by clootas** [comment]
That fixed it for me I think!

**Comment by FynnWaelsing** [comment]
This sounds exactly like the issue I mentioned before. Reposting what I said there and closing that issue.
-----------------
I've had the same issue with several different worlds now using Strange. World loads fine at first, everything seems to be normal. Then after maybe 15-30 minutes I start getting lots of tps lag which gets worse and worse over time (upwards of 500-600 ms ticks, maybe higher). Removing or disabling Strange returns it back to the normal 20 ms ticks.

Strange Version: Strange-1.15.2-1.0.0-beta.1.
Forge Version: 31.1.35

**Comment by svenhjol** [comment]
Please test with this version of Strange:
https://github.com/svenhjol/Strange/releases/download/1.15.2-1.0.0-beta.2/Strange-1.15.2-1.0.0-beta.2-NOCOMPASS.jar

**Comment by clootas** [comment]
This problems fixed after updating to the latest CurseForge versions. Thanks!

**Comment by FynnWaelsing** [comment]
I haven't had any lag issues either since updating to the latest version. Thanks!

**Comment by svenhjol** [comment]
Thanks for testing.
