### ISSUE TITLE
[1.14] Totem of preserving appears without Totem

### ISSUE THREAD

**Issue by D-Bigboy-302** [svenhjol/Strange#21]
Every Time I die, regardless of gamemode or situation, a totem of preserving appears and stores items. Even if there is no totem in inventory or any items in inventory.

It also appears to completely override any death chest or tombstone mod.

**Comment by FynnWaelsing** [comment]
I had the same issue, but on 1.15.

**Comment by svenhjol** [comment]
The totem is actually designed to drop any time on death, rather than just being in your inventory. Apologies if that's a bit confusing - it was meant to be the same as the Quark "Totem of Holding" from 1.12.

However, the death chest / tombstone mod override is not correct behavior. Please could you let me know which mods these are so I can blacklist them?

**Comment by svenhjol** [comment]
Behavior of the totem has now been changed. By default, you must be holding a totem for it to protect your items rather than spawning one all the time. This is configurable.

**Comment by D-Bigboy-302** [comment]
Hey! Sorry for being a bit late, not sure if it matters since the problem has been fixed now. I tested out the latest version.

The mods I was talking about were Corail's Tombstone mod and the Corpse mod.

Incase this information helps, thanks again! Love your mods!

**Comment by svenhjol** [comment]
Thank you, I'll check compatibility with them.
