### ISSUE TITLE
Removing the mod causes certain chunks to not load properly, and then crashes the game.

### ISSUE THREAD

**Issue by Bananna50** [svenhjol/Strange#43]
I changed my mind on the mod and decided to remove it. Whenever I would head to the nearby swamp it would crash afterwards. Re-installing the mod fixed it though (With a lot of chunk errors but it's fine) I have included the crash report just in case it is useful. Let me know if you need anything else, or if I messed up somehow, since I am new to this.

[crash-2020-04-26_17.53.12-server.txt](https://github.com/svenhjol/Strange/files/4539206/crash-2020-04-26_17.53.12-server.txt)

**Comment by svenhjol** [comment]
Removing Quark from a generated world causes this error with BIg Dungeons:
`[Server thread/ERROR] [minecraft/Structures]: Unknown feature id: quark:big_dungeon`
but doesn't crash the chunk generator.
I must be doing something different with the Strange structures but I can't see what.

**Comment by svenhjol** [comment]
Still looking for help with structure registration. Any devs?

**Comment by dkmk100** [comment]
I also had this issue please fix it!

**Comment by svenhjol** [comment]
Bump. Still looking for help from devs.

**Comment by svenhjol** [comment]
After debugging, this is a Minecraft registration and chunk serialize/deserialize problem. For example, removing Quark from the game will cause the same crash if you visit an area that would have spawned a Big Dungeon structure.

From `ChunkGenerator.java:188`:
```java
StructureStart structurestart = entry.getValue();
```
does not check if `structurestart` is `null` before attempting to check its bounding box.
The chunk serializer stores all registered structure IDs. If a mod is removed, the ID will persist in the world but the code to build the structure will no longer be present, so at this point `structurestart` will be `null` for that missing structure ID; consequently, this method crashes with a `NullPointerException`.

This will probably need to be brought to Forge's attention, since Mojang won't have any interest in fixing custom structures. It's out of my hands now.
