### ISSUE TITLE
Vaults generate above ground

### ISSUE THREAD

**Issue by dabomb6405** [svenhjol/Strange#80]
In the outer lands, I have seen vaults generating above the ground without a stone circle in sight. I know this isn’t how they are supposed to generate and this is a bug that really needs fixing.

**Comment by svenhjol** [comment]
Hi,

In order for us to have a chance at fixing it, we need to know the following:
* what version of Strange
* what version of Forge
* the world seed
* coordinates of where the bug is happening
* any modifications you made to the config (for example, changing the maximum height of the vaults from 62 to another number)

**Comment by svenhjol** [comment]
No response. Please reopen if you need assistance.
